version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html

hooks:
  ApplicationStop:
    - location: scripts/stop_application
      runas: root
      timeout: 300
  BeforeInstall:
    - location: scripts/configure_server
      timeout: 300
      runas: root
    - location: scripts/prepare_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
    - location: scripts/install_crontab
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application
      runas: root
      timeout: 300