version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html
  - source: /configs/intuit.conf
    destination: /etc/apache2/sites-enabled/
  - source: /configs/www.conf
    destination: /etc/php5/fpm/pool.d/
  - source: /configs
    destination: /root/configs
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_application
      runas: root
      timeout: 300
  BeforeInstall:
    - location: scripts/configure_server
      timeout: 300
      runas: root
    - location: scripts/prepare_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application
      runas: root
      timeout: 300