#!/bin/bash
#####
# Move existing code base
#####
if [ -d "/var/www/html" ];
  then
    rm -rf /var/www/html.bk
    mv -f /var/www/html /var/www/html.bk;
  else
    echo "Web directory /var/www/html not installed... are we ubuntu?";
fi
